/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
 This plugin is a direct copy of Image2 with added logic to handle sizing images by percentages.
*/
(function(){function E(a){function b(){this.deflated||(a.widgets.focused==this.widget&&(this.focused=!0),a.widgets.destroy(this.widget),this.deflated=!0)}function f(){var d=a.editable(),g=a.document;if(this.deflated)this.widget=a.widgets.initOn(this.element,"image",this.widget.data),this.widget.inline&&!(new CKEDITOR.dom.elementPath(this.widget.wrapper,d)).block&&(d=g.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div"),d.replace(this.widget.wrapper),this.widget.wrapper.move(d)),this.focused&&
(this.widget.focus(),delete this.focused),delete this.deflated;else{var b=this.widget,d=e,g=b.wrapper,c=b.data.align,b=b.data.hasCaption;if(d){for(var n=3;n--;)g.removeClass(d[n]);"center"==c?b&&g.addClass(d[1]):"none"!=c&&g.addClass(d[w[c]])}else"center"==c?(b?g.setStyle("text-align","center"):g.removeStyle("text-align"),g.removeStyle("float")):("none"==c?g.removeStyle("float"):g.setStyle("float",c),g.removeStyle("text-align"))}}var e=a.config.image3_alignClasses,c=a.config.image3_captionedClass;
return{allowedContent:F(a),requiredContent:"img[src,alt]",features:G(a),styleableElements:"img figure",contentTransformations:[],editables:{caption:{selector:"figcaption",allowedContent:"br em strong sub sup u s; a[!href,target]"}},parts:{image:"img",caption:"figcaption"},dialog:"image3",template:'\x3cimg alt\x3d"" src\x3d"" /\x3e',data:function(){var d=this.features;this.data.hasCaption&&!a.filter.checkFeature(d.caption)&&(this.data.hasCaption=!1);"none"==this.data.align||a.filter.checkFeature(d.align)||
(this.data.align="none");this.shiftState({widget:this,element:this.element,oldData:this.oldData,newData:this.data,deflate:b,inflate:f});this.data.link?this.parts.link||(this.parts.link=this.parts.image.getParent()):this.parts.link&&delete this.parts.link;this.parts.image.setAttributes({src:this.data.src,"data-cke-saved-src":this.data.src,alt:this.data.alt});if(this.oldData&&!this.oldData.hasCaption&&this.data.hasCaption)for(var g in this.data.classes)this.parts.image.removeClass(g);if(a.filter.checkFeature(d.dimension)){d=
this.data;g={width:d.width,height:d.height};var e=this.parts.image,c=this.wrapper,n=this.resizeWrapper,B=this.element;"center"==this.data.align&&n&&(c=n);if(d.sizeImageBy==CKEDITOR.plugins.image3.PERCENT)for(var h in g){var n=parseInt(e.getStyle("border-width"))||0,m;if("width"==h){m=parseInt(e.getStyle("margin-left"))||0;var p=parseInt(e.getStyle("margin-right"))||0;m=2*n+m+p;e.setStyle("width","calc(100% - "+m+"px)")}else"height"==h&&(m=parseInt(e.getStyle("margin-top"))||0,p=parseInt(e.getStyle("margin-bottom"))||
0,m=2*n+m+p,e.setStyle("height","calc(100% - "+m+"px)"));d.hasCaption&&B&&B.setStyle(h,"100%");c&&(g[h]?c.setStyle(h,"calc("+g[h]+d.sizeImageBy+" + "+m+"px)"):c.removeStyle(h))}else for(h in g)c&&c.removeStyle(h),n&&n.removeStyle(h),d.hasCaption&&B&&B.removeStyle(h),g[h]?e.setAttribute(h,g[h]+d.sizeImageBy):e.removeAttribute(h),e.removeStyle(h)}this.oldData=CKEDITOR.tools.extend({},this.data)},init:function(){var d=CKEDITOR.plugins.image3,b=this.parts.image,c={hasCaption:!!this.parts.caption,src:b.getAttribute("src"),
alt:b.getAttribute("alt")||"",width:b.getAttribute("width")||"",height:b.getAttribute("height")||"",lock:this.ready?d.checkHasNaturalRatio(b):!0};-1==c.width.indexOf(d.PERCENT)&&-1==c.height.indexOf(d.PERCENT)?c.sizeImageBy="px":c.sizeImageBy=d.PERCENT;c.width=parseInt(c.width);c.height=parseInt(c.height);var f=b.getAscendant("a");f&&this.wrapper.contains(f)&&(this.parts.link=f);c.align||(b=c.hasCaption?this.element:b,e?(b.hasClass(e[0])?c.align="left":b.hasClass(e[2])&&(c.align="right"),c.align?
b.removeClass(e[w[c.align]]):c.align="none"):(c.align=b.getStyle("float")||"none",b.removeStyle("float")));a.plugins.link&&this.parts.link&&(c.link=d.getLinkAttributesParser()(a,this.parts.link),(b=c.link.advanced)&&b.advCSSClasses&&(b.advCSSClasses=CKEDITOR.tools.trim(b.advCSSClasses.replace(/cke_\S+/,""))));this.wrapper[(c.hasCaption?"remove":"add")+"Class"]("cke_image_nocaption");this.setData(c);a.filter.checkFeature(this.features.dimension)&&!0!==a.config.image3_disableResizer&&1!=a.readOnly&&
H(this);this.shiftState=d.stateShifter(this.editor);this.on("contextMenu",function(a){a.data.image=CKEDITOR.TRISTATE_OFF;if(this.parts.link||this.wrapper.getAscendant("a"))a.data.link=a.data.unlink=CKEDITOR.TRISTATE_OFF});this.on("dialog",function(a){a.data.widget=this},this)},addClass:function(a){t(this).addClass(a)},hasClass:function(a){return t(this).hasClass(a)},removeClass:function(a){t(this).removeClass(a)},getClasses:function(){var a=new RegExp("^("+[].concat(c,e).join("|")+")$");return function(){var c=
this.repository.parseElementClasses(t(this).getAttribute("class")),b;for(b in c)a.test(b)&&delete c[b];return c}}(),upcast:I(a),downcast:J(a),getLabel:function(){return this.editor.lang.widget.label.replace(/%1/,(this.data.alt||"")+" "+this.pathName)}}}function I(a){var b=u(a),f=a.config.image3_captionedClass;return function(a,c){var d=a.name,g;if(!a.attributes["data-cke-realelement"]&&(b(a)?("div"==d&&(d=a.getFirst("figure"))&&(a.replaceWith(d),a=d),c.align="center",g=a.getFirst("img")||a.getFirst("a").getFirst("img")):
"figure"==d&&a.hasClass(f)?g=a.getFirst("img")||a.getFirst("a").getFirst("img"):x(a)&&(g="a"==a.name?a.children[0]:a),g))return a}}function J(a){var b=a.config.image3_alignClasses;return function(f){var e="a"==f.name?f.getFirst():f,c=e.attributes,d=this.data.align;if(!this.inline){var g=f.getFirst("span");g&&g.replaceWith(g.getFirst({img:1,a:1}))}d&&"none"!=d&&(g=CKEDITOR.tools.parseCssText(c.style||""),"center"==d&&"figure"==f.name?f=f.wrapWith(new CKEDITOR.htmlParser.element("div",b?{"class":b[1]}:
{style:"text-align:center"})):d in{left:1,right:1}&&(b?e.addClass(b[w[d]]):g["float"]=d),b||CKEDITOR.tools.isEmpty(g)||(c.style=CKEDITOR.tools.writeCssText(g)));c=CKEDITOR.plugins.image3;a.filter.checkFeature(this.features.dimension)&&(e=this.data,e.sizeImageBy==c.PERCENT&&(c="img"==f.name?f:f.find("img")[0],e.width&&(c.attributes.width=e.width+e.sizeImageBy),e.height&&(c.attributes.height=e.height+e.sizeImageBy),c.removeStyle("width"),c.removeStyle("height")));return f}}function u(a){var b=a.config.image3_captionedClass,
f=a.config.image3_alignClasses,e={figure:1,a:1,img:1};return function(c){if(!(c.name in{div:1,p:1}))return!1;var d=c.children;if(1!==d.length)return!1;d=d[0];if(!(d.name in e))return!1;if("p"==c.name){if(!x(d))return!1}else if("figure"==d.name){if(!d.hasClass(b))return!1}else if(a.enterMode==CKEDITOR.ENTER_P||!x(d))return!1;return(f?c.hasClass(f[1]):"center"==CKEDITOR.tools.parseCssText(c.attributes.style||"",!0)["text-align"])?!0:!1}}function x(a){return"img"==a.name?!0:"a"==a.name?1==a.children.length&&
a.getFirst("img"):!1}function H(a){var b=a.editor,f=b.editable(),e=b.document,c=a.resizer=e.createElement("span");c.addClass("cke_image_resizer");c.setAttribute("title",b.lang.image3.resizer);c.append(new CKEDITOR.dom.text("​",e));if(a.inline)a.wrapper.append(c);else{var d=a.parts.link||a.parts.image,g=d.getParent(),k=e.createElement("span");k.addClass("cke_image_resizer_wrapper");k.append(d);k.append(c);a.element.append(k,!0);a.resizeWrapper=k;g.is("span")&&g.remove()}c.on("mousedown",function(d){function n(a,
c,b){var d=CKEDITOR.document,h=[];e.equals(d)||h.push(d.on(a,c));h.push(e.on(a,c));if(b)for(a=h.length;a--;)b.push(h.pop())}function g(){q=t+k*z;r=Math.round(q/y)}function h(){r=w-v;q=Math.round(r*y)}var m=CKEDITOR.plugins.image3,p=a.parts.image,k="right"==a.data.align?-1:1,K=d.data.$.screenX,l=d.data.$.screenY,t=p.$.clientWidth,w=p.$.clientHeight,y=t/w,u=[],x="cke_image_s"+(~k?"e":"w"),C,q,r,D,z,v,A;b.fire("saveSnapshot");n("mousemove",function(c){C=c.data.$;z=C.screenX-K;v=l-C.screenY;A=Math.abs(z/
v);1==k?0>=z?0>=v?g():A>=y?g():h():0>=v?A>=y?h():g():h():0>=z?0>=v?A>=y?h():g():h():0>=v?g():A>=y?g():h();D=!0;15<=q&&15<=r&&(p.setAttributes({width:q,height:r}),p.removeStyle("width"),p.removeStyle("height"),a.resizeWrapper&&(a.resizeWrapper.removeStyle("width"),a.resizeWrapper.removeStyle("height")),a.wrapper&&(a.wrapper.removeStyle("width"),a.wrapper.removeStyle("height")))},u);n("mouseup",function(){for(var d;d=u.pop();)d.removeListener();f.removeClass(x);c.removeClass("cke_image_resizing");a.data.sizeImageBy==
m.PERCENT?(d={width:p.getAttribute("width"),height:p.getAttribute("height")},d=m.convertDimensionsTo(a,d,m.PERCENT,m.getNatural),q=d.width,r=d.height):(q=parseInt(p.getAttribute("width"),10),r=parseInt(p.getAttribute("height"),10));D&&q&&r&&a.setData({width:q,height:r});b.fire("saveSnapshot");D=!1},u);f.addClass(x);c.addClass("cke_image_resizing")});a.on("data",function(){c["right"==a.data.align?"addClass":"removeClass"]("cke_image_resizer_left")})}function L(a){var b=[],f;return function(e){var c=
a.getCommand("justify"+e);if(c){b.push(function(){c.refresh(a,a.elementPath())});if(e in{right:1,left:1,center:1})c.on("exec",function(c){var g=l(a);if(g){g.setData("align",e);for(g=b.length;g--;)b[g]();c.cancel()}});c.on("refresh",function(c){var b=l(a),k={right:1,left:1,center:1};b&&(void 0===f&&(f=a.filter.checkFeature(a.widgets.registered.image.features.align)),f?this.setState(b.data.align==e?CKEDITOR.TRISTATE_ON:e in k?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED):this.setState(CKEDITOR.TRISTATE_DISABLED),
c.cancel())})}}}function M(a){a.plugins.link&&(CKEDITOR.on("dialogDefinition",function(b){b=b.data;if("link"==b.name){b=b.definition;var f=b.onShow,e=b.onOk;b.onShow=function(){var c=l(a),b=this.getContentElement("info","linkDisplayText").getElement().getParent().getParent();c&&(c.inline?!c.wrapper.getAscendant("a"):1)?(this.setupContent(c.data.link||{}),b.hide()):(b.show(),f.apply(this,arguments))};b.onOk=function(){var c=l(a);if(c&&(c.inline?!c.wrapper.getAscendant("a"):1)){var b={};this.commitContent(b);
c.setData("link",b)}else e.apply(this,arguments)}}}),a.getCommand("unlink").on("exec",function(b){var f=l(a);f&&f.parts.link&&(f.setData("link",null),this.refresh(a,a.elementPath()),b.cancel())}),a.getCommand("unlink").on("refresh",function(b){var f=l(a);f&&(this.setState(f.data.link||f.wrapper.getAscendant("a")?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED),b.cancel())}))}function l(a){return(a=a.widgets.focused)&&"image"==a.name?a:null}function F(a){var b=a.config.image3_alignClasses;a={div:{match:u(a)},
p:{match:u(a)},img:{attributes:"!src,alt,width,height",styles:"border-style,border-width,float,height,margin,margin-bottom,margin-left,margin-right,margin-top,width"},figure:{classes:"!"+a.config.image3_captionedClass},figcaption:!0};b?(a.div.classes=b[1],a.p.classes=a.div.classes,a.img.classes=b[0]+","+b[2],a.figure.classes+=","+a.img.classes):(a.div.styles="text-align",a.p.styles="text-align",a.figure.styles="float,display");return a}function G(a){a=a.config.image3_alignClasses;return{dimension:{requiredContent:"img[width,height]"},
align:{requiredContent:"img"+(a?"("+a[0]+")":"{float}")},caption:{requiredContent:"figcaption"}}}function t(a){return a.data.hasCaption?a.element:a.parts.image}var N=new CKEDITOR.template('\x3cfigure class\x3d"{captionedClass}"\x3e\x3cimg alt\x3d"" src\x3d"" /\x3e\x3cfigcaption\x3e{captionPlaceholder}\x3c/figcaption\x3e\x3c/figure\x3e'),w={left:0,center:1,right:2};CKEDITOR.plugins.add("image3",{lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",
requires:"widget,dialog",icons:"image",hidpi:!0,onLoad:function(){CKEDITOR.addCss(".cke_image_nocaption{line-height:0}.cke_editable.cke_image_sw, .cke_editable.cke_image_sw *{cursor:sw-resize !important}.cke_editable.cke_image_se, .cke_editable.cke_image_se *{cursor:se-resize !important}.cke_image_resizer{display:none;position:absolute;width:10px;height:10px;bottom:-5px;right:-5px;background:#000;outline:1px solid #fff;line-height:0;cursor:se-resize;}.cke_image_resizer_wrapper{position:relative;display:inline-block;line-height:0;}.cke_image_resizer.cke_image_resizer_left{right:auto;left:-5px;cursor:sw-resize;}.cke_widget_wrapper:hover .cke_image_resizer,.cke_image_resizer.cke_image_resizing{display:block}.cke_widget_wrapper\x3ea{display:inline-block}")},
init:function(a){var b=a.config,f=a.lang.image3,e=E(a);b.filebrowserImage3BrowseUrl=b.filebrowserImageBrowseUrl;b.filebrowserImage3UploadUrl=b.filebrowserImageUploadUrl;e.pathName=f.pathName;e.editables.caption.pathName=f.pathNameCaption;a.widgets.add("image",e);a.ui.addButton&&a.ui.addButton("Image",{label:a.lang.common.resize,command:"image",toolbar:"insert,10"});a.contextMenu&&(a.addMenuGroup("image",10),a.addMenuItem("image",{label:f.menu,command:"image",group:"image"}));CKEDITOR.dialog.add("image3",
this.path+"dialogs/image3.js")},afterInit:function(a){var b={left:1,right:1,center:1,block:1},f=L(a),e;for(e in b)f(e);M(a)}});CKEDITOR.plugins.image3={PERCENT:"%",PIXEL:"px",stateShifter:function(a){function b(a,b){var d={};c?d.attributes={"class":c[1]}:d.styles={"text-align":"center"};d=e.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div",d);f(d,b);b.move(d);return d}function f(b,c){if(c.getParent()){var d=a.createRange();d.moveToPosition(c,CKEDITOR.POSITION_BEFORE_START);c.remove();g.insertElementIntoRange(b,
d)}else b.replace(c)}var e=a.document,c=a.config.image3_alignClasses,d=a.config.image3_captionedClass,g=a.editable(),k=["hasCaption","align","link"],l={align:function(d,e,h){var f=d.element;d.changed.align?d.newData.hasCaption||("center"==h&&(d.deflate(),d.element=b(a,f)),d.changed.hasCaption||"center"!=e||"center"==h||(d.deflate(),e=f.findOne("a,img"),e.replace(f),d.element=e)):"center"==h&&d.changed.hasCaption&&!d.newData.hasCaption&&(d.deflate(),d.element=b(a,f));!c&&f.is("figure")&&("center"==
h?f.setStyle("display","inline-block"):f.removeStyle("display"))},hasCaption:function(b,c,h){b.changed.hasCaption&&(c=b.element.is({img:1,a:1})?b.element:b.element.findOne("a,img"),b.deflate(),h?(h=CKEDITOR.dom.element.createFromHtml(N.output({captionedClass:d,captionPlaceholder:a.lang.image3.captionPlaceholder}),e),f(h,b.element),c.replace(h.findOne("img")),b.element=h):(c.replace(b.element),b.element=c))},link:function(b,c,d){if(b.changed.link){var f=b.element.is("img")?b.element:b.element.findOne("img"),
g=b.element.is("a")?b.element:b.element.findOne("a"),k=b.element.is("a")&&!d||b.element.is("img")&&d,l;k&&b.deflate();d?(c||(l=e.createElement("a",{attributes:{href:b.newData.link.url}}),l.replace(f),f.move(l)),d=CKEDITOR.plugins.image3.getLinkAttributesGetter()(a,d),CKEDITOR.tools.isEmpty(d.set)||(l||g).setAttributes(d.set),d.removed.length&&(l||g).removeAttributes(d.removed)):(d=g.findOne("img"),d.replace(g),l=d);k&&(b.element=l)}}};return function(a){var b,c;a.changed={};for(c=0;c<k.length;c++)b=
k[c],a.changed[b]=a.oldData?a.oldData[b]!==a.newData[b]:!1;for(c=0;c<k.length;c++)b=k[c],l[b](a,a.oldData?a.oldData[b]:null,a.newData[b]);a.inflate()}},checkHasNaturalRatio:function(a){var b=a.$;a=this.getNatural(a);return Math.round(b.clientWidth/a.width*a.height)==b.clientHeight||Math.round(b.clientHeight/a.height*a.width)==b.clientWidth},getNatural:function(a){if(a.$.naturalWidth)a={width:a.$.naturalWidth,height:a.$.naturalHeight};else{var b=new Image;b.src=a.getAttribute("src");a={width:b.width,
height:b.height}}return a},convertDimensionsTo:function(a,b,f,e){var c=a.wrapper.getParent().getClientRect(),d=c.width,c=c.height;void 0==typeof e&&(e=this.getNatural(a.parts.image));a={width:0,height:0};f==this.PIXEL?(a.width=Math.round(b.width/100*d),a.height=Math.round((e.height||1)/(e.width||1)*a.width)):f==this.PERCENT&&(0==d&&(d=1),0==c&&(c=1),a.height=Math.round(b.height/c*100),a.width=Math.round(b.width/d*100));return a},getLinkAttributesGetter:function(){return CKEDITOR.plugins.link.getLinkAttributes},
getLinkAttributesParser:function(){return CKEDITOR.plugins.link.parseLinkAttributes}}})();CKEDITOR.config.image3_captionedClass="image";