/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
 This plugin is a direct copy of Image2 with added logic to handle sizing images by percentages.
*/
(function(){function G(a){function b(){this.deflated||(a.widgets.focused==this.widget&&(this.focused=!0),a.widgets.destroy(this.widget),this.deflated=!0)}function e(){var d=a.editable(),c=a.document;if(this.deflated)this.widget=a.widgets.initOn(this.element,"image",this.widget.data),this.widget.inline&&!(new CKEDITOR.dom.elementPath(this.widget.wrapper,d)).block&&(d=c.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div"),d.replace(this.widget.wrapper),this.widget.wrapper.move(d)),this.focused&&
(this.widget.focus(),delete this.focused),delete this.deflated;else{var b=this.widget,d=f,c=b.wrapper,e=b.data.align,b=b.data.hasCaption;if(d){for(var l=3;l--;)c.removeClass(d[l]);"center"==e?b&&c.addClass(d[1]):"none"!=e&&c.addClass(d[y[e]])}else"center"==e?(b?c.setStyle("text-align","center"):c.removeStyle("text-align"),c.removeStyle("float")):("none"==e?c.removeStyle("float"):c.setStyle("float",e),c.removeStyle("text-align"))}}var f=a.config.image3_alignClasses,g=a.config.image3_captionedClass;
return{allowedContent:H(a),requiredContent:"img[src,alt]",features:I(a),styleableElements:"img figure",contentTransformations:[],editables:{caption:{selector:"figcaption",allowedContent:"br em strong sub sup u s; a[!href,target]"}},parts:{image:"img",caption:"figcaption"},dialog:"image3",template:'\x3cimg alt\x3d"" src\x3d"" /\x3e',data:function(){var d=this.features;this.data.hasCaption&&!a.filter.checkFeature(d.caption)&&(this.data.hasCaption=!1);"none"==this.data.align||a.filter.checkFeature(d.align)||
(this.data.align="none");this.shiftState({widget:this,element:this.element,oldData:this.oldData,newData:this.data,deflate:b,inflate:e});this.data.link?this.parts.link||(this.parts.link=this.parts.image.getParent()):this.parts.link&&delete this.parts.link;this.parts.image.setAttributes({src:this.data.src,"data-cke-saved-src":this.data.src,alt:this.data.alt});if(this.oldData&&!this.oldData.hasCaption&&this.data.hasCaption)for(var c in this.data.classes)this.parts.image.removeClass(c);if(a.filter.checkFeature(d.dimension)){d=
this.data;c={width:d.width,height:d.height};var f=this.parts.image,g=this.wrapper,l=this.resizeWrapper,m=this.element;"center"==this.data.align&&l&&(g=l);if("%"==d.sizeImageBy)for(var h in c)f.setAttribute(h,"100%"),d.hasCaption&&m&&m.setStyle(h,"100%"),g&&(c[h]?g.setStyle(h,c[h]+d.sizeImageBy):g.removeStyle(h));else for(h in c)g&&g.removeStyle(h),l&&l.removeStyle(h),d.hasCaption&&m&&m.removeStyle(h,"100%"),c[h]?f.setAttribute(h,c[h]+d.sizeImageBy):f.removeAttribute(h)}this.oldData=CKEDITOR.tools.extend({},
this.data)},init:function(){var d=CKEDITOR.plugins.image3,c=this.parts.image,b={hasCaption:!!this.parts.caption,src:c.getAttribute("src"),alt:c.getAttribute("alt")||"",width:c.getAttribute("width")||"",height:c.getAttribute("height")||"",lock:this.ready?d.checkHasNaturalRatio(c):!0};-1==b.width.indexOf("%")&&-1==b.height.indexOf("%")?b.sizeImageBy="px":b.sizeImageBy="%";b.width=parseInt(b.width);b.height=parseInt(b.height);var e=c.getAscendant("a");e&&this.wrapper.contains(e)&&(this.parts.link=e);
b.align||(c=b.hasCaption?this.element:c,f?(c.hasClass(f[0])?b.align="left":c.hasClass(f[2])&&(b.align="right"),b.align?c.removeClass(f[y[b.align]]):b.align="none"):(b.align=c.getStyle("float")||"none",c.removeStyle("float")));a.plugins.link&&this.parts.link&&(b.link=d.getLinkAttributesParser()(a,this.parts.link),(c=b.link.advanced)&&c.advCSSClasses&&(c.advCSSClasses=CKEDITOR.tools.trim(c.advCSSClasses.replace(/cke_\S+/,""))));this.wrapper[(b.hasCaption?"remove":"add")+"Class"]("cke_image_nocaption");
this.setData(b);a.filter.checkFeature(this.features.dimension)&&!0!==a.config.image3_disableResizer&&1!=a.readOnly&&J(this);this.shiftState=d.stateShifter(this.editor);this.on("contextMenu",function(a){a.data.image=CKEDITOR.TRISTATE_OFF;if(this.parts.link||this.wrapper.getAscendant("a"))a.data.link=a.data.unlink=CKEDITOR.TRISTATE_OFF});this.on("dialog",function(a){a.data.widget=this},this)},addClass:function(a){r(this).addClass(a)},hasClass:function(a){return r(this).hasClass(a)},removeClass:function(a){r(this).removeClass(a)},
getClasses:function(){var a=new RegExp("^("+[].concat(g,f).join("|")+")$");return function(){var b=this.repository.parseElementClasses(r(this).getAttribute("class")),f;for(f in b)a.test(f)&&delete b[f];return b}}(),upcast:K(a),downcast:L(a),getLabel:function(){return this.editor.lang.widget.label.replace(/%1/,(this.data.alt||"")+" "+this.pathName)}}}function K(a){var b=t(a),e=a.config.image3_captionedClass;return function(a,g){var d=a.name,c;if(!a.attributes["data-cke-realelement"]&&(b(a)?("div"==
d&&(d=a.getFirst("figure"))&&(a.replaceWith(d),a=d),g.align="center",c=a.getFirst("img")||a.getFirst("a").getFirst("img")):"figure"==d&&a.hasClass(e)?c=a.getFirst("img")||a.getFirst("a").getFirst("img"):u(a)&&(c="a"==a.name?a.children[0]:a),c))return a}}function L(a){var b=a.config.image3_alignClasses;return function(e){var f="a"==e.name?e.getFirst():e,g=f.attributes,d=this.data.align;if(!this.inline){var c=e.getFirst("span");c&&c.replaceWith(c.getFirst({img:1,a:1}))}d&&"none"!=d&&(c=CKEDITOR.tools.parseCssText(g.style||
""),"center"==d&&"figure"==e.name?e=e.wrapWith(new CKEDITOR.htmlParser.element("div",b?{"class":b[1]}:{style:"text-align:center"})):d in{left:1,right:1}&&(b?f.addClass(b[y[d]]):c["float"]=d),b||CKEDITOR.tools.isEmpty(c)||(g.style=CKEDITOR.tools.writeCssText(c)));a.filter.checkFeature(this.features.dimension)&&"%"==this.data.sizeImageBy&&(this.data.width&&(f.attributes.width=this.data.width+this.data.sizeImageBy),this.data.height&&(f.attributes.height=this.data.height+this.data.sizeImageBy));return e}}
function t(a){var b=a.config.image3_captionedClass,e=a.config.image3_alignClasses,f={figure:1,a:1,img:1};return function(g){if(!(g.name in{div:1,p:1}))return!1;var d=g.children;if(1!==d.length)return!1;d=d[0];if(!(d.name in f))return!1;if("p"==g.name){if(!u(d))return!1}else if("figure"==d.name){if(!d.hasClass(b))return!1}else if(a.enterMode==CKEDITOR.ENTER_P||!u(d))return!1;return(e?g.hasClass(e[1]):"center"==CKEDITOR.tools.parseCssText(g.attributes.style||"",!0)["text-align"])?!0:!1}}function u(a){return"img"==
a.name?!0:"a"==a.name?1==a.children.length&&a.getFirst("img"):!1}function J(a){var b=a.editor,e=b.editable(),f=b.document,g=a.resizer=f.createElement("span");g.addClass("cke_image_resizer");g.setAttribute("title",b.lang.image3.resizer);g.append(new CKEDITOR.dom.text("​",f));if(a.inline)a.wrapper.append(g);else{var d=a.parts.link||a.parts.image,c=d.getParent(),k=f.createElement("span");k.addClass("cke_image_resizer_wrapper");k.append(d);k.append(g);a.element.append(k,!0);a.resizeWrapper=k;c.is("span")&&
c.remove()}g.on("mousedown",function(c){function d(a,b,c){var h=CKEDITOR.document,l=[];f.equals(h)||l.push(h.on(a,b));l.push(f.on(a,b));if(c)for(a=l.length;a--;)c.push(l.pop())}function m(){v=t+n*z;w=Math.round(v/x)}function h(){w=u-q;v=Math.round(w*x)}function k(a){C=a.data.$;z=C.screenX-r;q=y-C.screenY;A=Math.abs(z/q);1==n?0>=z?0>=q?m():A>=x?m():h():0>=q?A>=x?h():m():h():0>=z?0>=q?A>=x?h():m():h():0>=q?m():A>=x?m():h();15<=v&&15<=w?(D.setAttributes({width:v,height:w}),B=!0):B=!1}function p(){for(var c;c=
E.pop();)c.removeListener();e.removeClass(F);g.removeClass("cke_image_resizing");B&&(a.setData({width:v,height:w}),b.fire("saveSnapshot"));B=!1}if("%"!=a.data.sizeImageBy){var D=a.parts.image,n="right"==a.data.align?-1:1,r=c.data.$.screenX,y=c.data.$.screenY,t=D.$.clientWidth,u=D.$.clientHeight,x=t/u,E=[],F="cke_image_s"+(~n?"e":"w"),C,v,w,B,z,q,A;b.fire("saveSnapshot");d("mousemove",k,E);d("mouseup",p,E);e.addClass(F);g.addClass("cke_image_resizing")}});a.on("data",function(){g["right"==a.data.align?
"addClass":"removeClass"]("cke_image_resizer_left")})}function M(a){var b=[],e;return function(f){var g=a.getCommand("justify"+f);if(g){b.push(function(){g.refresh(a,a.elementPath())});if(f in{right:1,left:1,center:1})g.on("exec",function(d){var c=p(a);if(c){c.setData("align",f);for(c=b.length;c--;)b[c]();d.cancel()}});g.on("refresh",function(b){var c=p(a),g={right:1,left:1,center:1};c&&(void 0===e&&(e=a.filter.checkFeature(a.widgets.registered.image.features.align)),e?this.setState(c.data.align==
f?CKEDITOR.TRISTATE_ON:f in g?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED):this.setState(CKEDITOR.TRISTATE_DISABLED),b.cancel())})}}}function N(a){a.plugins.link&&(CKEDITOR.on("dialogDefinition",function(b){b=b.data;if("link"==b.name){b=b.definition;var e=b.onShow,f=b.onOk;b.onShow=function(){var b=p(a),d=this.getContentElement("info","linkDisplayText").getElement().getParent().getParent();b&&(b.inline?!b.wrapper.getAscendant("a"):1)?(this.setupContent(b.data.link||{}),d.hide()):(d.show(),e.apply(this,
arguments))};b.onOk=function(){var b=p(a);if(b&&(b.inline?!b.wrapper.getAscendant("a"):1)){var d={};this.commitContent(d);b.setData("link",d)}else f.apply(this,arguments)}}}),a.getCommand("unlink").on("exec",function(b){var e=p(a);e&&e.parts.link&&(e.setData("link",null),this.refresh(a,a.elementPath()),b.cancel())}),a.getCommand("unlink").on("refresh",function(b){var e=p(a);e&&(this.setState(e.data.link||e.wrapper.getAscendant("a")?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED),b.cancel())}))}
function p(a){return(a=a.widgets.focused)&&"image"==a.name?a:null}function H(a){var b=a.config.image3_alignClasses;a={div:{match:t(a)},p:{match:t(a)},img:{attributes:"!src,alt,width,height",styles:"border-style,border-width,float,height,margin,margin-bottom,margin-left,margin-right,margin-top,width"},figure:{classes:"!"+a.config.image3_captionedClass},figcaption:!0};b?(a.div.classes=b[1],a.p.classes=a.div.classes,a.img.classes=b[0]+","+b[2],a.figure.classes+=","+a.img.classes):(a.div.styles="text-align",
a.p.styles="text-align",a.figure.styles="float,display");return a}function I(a){a=a.config.image3_alignClasses;return{dimension:{requiredContent:"img[width,height]"},align:{requiredContent:"img"+(a?"("+a[0]+")":"{float}")},caption:{requiredContent:"figcaption"}}}function r(a){return a.data.hasCaption?a.element:a.parts.image}var O=new CKEDITOR.template('\x3cfigure class\x3d"{captionedClass}"\x3e\x3cimg alt\x3d"" src\x3d"" /\x3e\x3cfigcaption\x3e{captionPlaceholder}\x3c/figcaption\x3e\x3c/figure\x3e'),
y={left:0,center:1,right:2};CKEDITOR.plugins.add("image3",{lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",requires:"widget,dialog",icons:"image",hidpi:!0,onLoad:function(){CKEDITOR.addCss(".cke_image_nocaption{line-height:0}.cke_editable.cke_image_sw, .cke_editable.cke_image_sw *{cursor:sw-resize !important}.cke_editable.cke_image_se, .cke_editable.cke_image_se *{cursor:se-resize !important}.cke_image_resizer{display:none;position:absolute;width:10px;height:10px;bottom:-5px;right:-5px;background:#000;outline:1px solid #fff;line-height:0;cursor:se-resize;}.cke_image_resizer_wrapper{position:relative;display:inline-block;line-height:0;}.cke_image_resizer.cke_image_resizer_left{right:auto;left:-5px;cursor:sw-resize;}.cke_widget_wrapper:hover .cke_image_resizer,.cke_image_resizer.cke_image_resizing{display:block}.cke_widget_wrapper\x3ea{display:inline-block}")},
init:function(a){var b=a.config,e=a.lang.image3,f=G(a);b.filebrowserImage3BrowseUrl=b.filebrowserImageBrowseUrl;b.filebrowserImage3UploadUrl=b.filebrowserImageUploadUrl;f.pathName=e.pathName;f.editables.caption.pathName=e.pathNameCaption;a.widgets.add("image",f);a.ui.addButton&&a.ui.addButton("Image",{label:a.lang.common.resize,command:"image",toolbar:"insert,10"});a.contextMenu&&(a.addMenuGroup("image",10),a.addMenuItem("image",{label:e.menu,command:"image",group:"image"}));CKEDITOR.dialog.add("image3",
this.path+"dialogs/image3.js")},afterInit:function(a){var b={left:1,right:1,center:1,block:1},e=M(a),f;for(f in b)e(f);N(a)}});CKEDITOR.plugins.image3={stateShifter:function(a){function b(a,b){var c={};g?c.attributes={"class":g[1]}:c.styles={"text-align":"center"};c=f.createElement(a.activeEnterMode==CKEDITOR.ENTER_P?"p":"div",c);e(c,b);b.move(c);return c}function e(b,d){if(d.getParent()){var h=a.createRange();h.moveToPosition(d,CKEDITOR.POSITION_BEFORE_START);d.remove();c.insertElementIntoRange(b,
h)}else b.replace(d)}var f=a.document,g=a.config.image3_alignClasses,d=a.config.image3_captionedClass,c=a.editable(),k=["hasCaption","align","link"],p={align:function(c,d,h){var e=c.element;c.changed.align?c.newData.hasCaption||("center"==h&&(c.deflate(),c.element=b(a,e)),c.changed.hasCaption||"center"!=d||"center"==h||(c.deflate(),d=e.findOne("a,img"),d.replace(e),c.element=d)):"center"==h&&c.changed.hasCaption&&!c.newData.hasCaption&&(c.deflate(),c.element=b(a,e));!g&&e.is("figure")&&("center"==
h?e.setStyle("display","inline-block"):e.removeStyle("display"))},hasCaption:function(b,c,h){b.changed.hasCaption&&(c=b.element.is({img:1,a:1})?b.element:b.element.findOne("a,img"),b.deflate(),h?(h=CKEDITOR.dom.element.createFromHtml(O.output({captionedClass:d,captionPlaceholder:a.lang.image3.captionPlaceholder}),f),e(h,b.element),c.replace(h.findOne("img")),b.element=h):(c.replace(b.element),b.element=c))},link:function(b,c,d){if(b.changed.link){var e=b.element.is("img")?b.element:b.element.findOne("img"),
g=b.element.is("a")?b.element:b.element.findOne("a"),k=b.element.is("a")&&!d||b.element.is("img")&&d,n;k&&b.deflate();d?(c||(n=f.createElement("a",{attributes:{href:b.newData.link.url}}),n.replace(e),e.move(n)),d=CKEDITOR.plugins.image3.getLinkAttributesGetter()(a,d),CKEDITOR.tools.isEmpty(d.set)||(n||g).setAttributes(d.set),d.removed.length&&(n||g).removeAttributes(d.removed)):(d=g.findOne("img"),d.replace(g),n=d);k&&(b.element=n)}}};return function(a){var b,c;a.changed={};for(c=0;c<k.length;c++)b=
k[c],a.changed[b]=a.oldData?a.oldData[b]!==a.newData[b]:!1;for(c=0;c<k.length;c++)b=k[c],p[b](a,a.oldData?a.oldData[b]:null,a.newData[b]);a.inflate()}},checkHasNaturalRatio:function(a){var b=a.$;a=this.getNatural(a);return Math.round(b.clientWidth/a.width*a.height)==b.clientHeight||Math.round(b.clientHeight/a.height*a.width)==b.clientWidth},getNatural:function(a){if(a.$.naturalWidth)a={width:a.$.naturalWidth,height:a.$.naturalHeight};else{var b=new Image;b.src=a.getAttribute("src");a={width:b.width,
height:b.height}}return a},getLinkAttributesGetter:function(){return CKEDITOR.plugins.link.getLinkAttributes},getLinkAttributesParser:function(){return CKEDITOR.plugins.link.parseLinkAttributes}}})();CKEDITOR.config.image3_captionedClass="image";