/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.dialog.add("image3",function(e){function D(){var a=this.getValue().match(E);(a=!(!a||0===parseInt(a[1],10)))||alert(c["invalid"+CKEDITOR.tools.capitalize(this.id)]);return a}function O(){function a(a,b){d.push(l.once(a,function(a){for(var l;l=d.pop();)l.removeListener();b(a)}))}var l=v.createElement("img"),d=[];return function(d,b,f){a("load",function(){var a=F(l);b.call(f,l,a.width,a.height)});a("error",function(){b(null)});a("abort",function(){b(null)});l.setAttribute("src",(z.baseHref||
"")+d+"?"+Math.random().toString(16).substring(2))}}function G(){var a=this.getValue();w(!1);a!==x.data.src?(H(a,function(a,d,b){w(!0);if(!a)return p(!1);f.setValue(!1===e.config.image3_prefillDimensions?0:d);k.setValue(!1===e.config.image3_prefillDimensions?0:b);q=d;r=b;p(I.checkHasNaturalRatio(a))}),t=!0):t?(w(!0),f.setValue(m),k.setValue(n),t=!1):w(!0)}function J(){if(g){var a=this.getValue();if(a&&(a.match(E)||p(!1),"0"!==a)){var b="width"==this.id,d=m||q,c=n||r,a=b?Math.round(a/d*c):Math.round(a/
c*d);isNaN(a)||(b?k:f).setValue(a)}}}function p(a){if(h){if("boolean"==typeof a){if(A)return;g=a}else a=f.getValue(),A=!0,(g=!g)&&a&&(a*=n/m,isNaN(a)||k.setValue(Math.round(a)));h[g?"removeClass":"addClass"]("cke_btn_unlocked");h.setAttribute("aria-checked",g);CKEDITOR.env.hc&&h.getChild(0).setHtml(g?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function w(a){a=a?"enable":"disable";f[a]();k[a]()}var E=/(^\s*(\d+)\s*$)|^$/i,K=CKEDITOR.tools.getNextId(),L=CKEDITOR.tools.getNextId(),b=e.lang.image3,
c=e.lang.common,P=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+b.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+
b.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:K,resetButtonId:L}),I=CKEDITOR.plugins.image3,z=e.config,B=!(!z.filebrowserImageBrowseUrl&&!z.filebrowserBrowseUrl),y=e.widgets.registered.image.features,F=I.getNatural,v,x,M,H,m,n,q,r,t,g,A,h,u,f,k,C,N=[{id:"src",type:"text",label:c.url,onKeyup:G,onChange:G,setup:function(a){this.setValue(a.data.src)},commit:function(a){a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];B&&N.push({type:"button",
id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:e.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:250,minHeight:100,onLoad:function(){v=this._.element.getDocument();H=O()},onShow:function(){x=this.widget;M=x.parts.image;t=A=g=!1;C=F(M);q=m=C.width;r=n=C.height},contents:[{id:"info",label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",children:N}]},{id:"alt",
type:"text",label:b.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())},validate:!0===e.config.image3_altRequired?CKEDITOR.dialog.validate.notEmpty(b.altMissing):null},{type:"hbox",widths:["100%"],requiredContent:y.dimension.requiredContent,children:[{type:"radio",width:"45px",id:"sizeimageby",label:b.sizeImageBy,onChange:function(){var a=this.getValue(),b={width:f.getValue(),height:k.getValue()},d=x.wrapper.getParent().getClientRect(),c=d.width,d=
d.height,g=n||r||1,h=m||q||1,e={width:0,height:0};"px"==a?(e.width=Math.round(b.width/100*c),e.height=Math.round(g/h*e.width)):(0==c&&(c=1),0==d&&(d=1),e.height=Math.round(b.height/d*100),e.width=Math.round(b.width/c*100));b=e;f.setValue(b.width);k.setValue(b.height)},items:[[b.pixels,"px"],[b.percentage,"%"]],onLoad:function(){},setup:function(a){this.setValue(a.data.sizeImageBy)},commit:function(a){a.setData("sizeImageBy",this.getValue())}}]},{type:"hbox",widths:["25%","25%","50%"],requiredContent:y.dimension.requiredContent,
children:[{type:"text",width:"45px",id:"width",label:c.width,validate:D,onKeyUp:J,onLoad:function(){f=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{type:"text",id:"height",width:"45px",label:c.height,validate:D,onKeyUp:J,onLoad:function(){k=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",
function(){this.addClass("cke_btn_over")},a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();h=v.getById(K);u=v.getById(L);h&&(b.addFocusable(h,4+B),h.on("click",function(a){p();a.data&&a.data.preventDefault()},this.getDialog()),a(h));u&&(b.addFocusable(u,5+B),u.on("click",function(a){t?(f.setValue(q),k.setValue(r)):(f.setValue(m),k.setValue(n));a.data&&a.data.preventDefault()},this),a(u))},setup:function(a){p(a.data.lock)},commit:function(a){a.setData("lock",
g)},html:P}]},{type:"hbox",id:"alignment",requiredContent:y.align.requiredContent,children:[{id:"align",type:"radio",items:[[c.alignNone,"none"],[c.alignLeft,"left"],[c.alignCenter,"center"],[c.alignRight,"right"]],label:c.align,setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:b.captioned,requiredContent:y.caption.requiredContent,setup:function(a){this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",
this.getValue())}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:b.btnUpload,"for":["Upload","upload"]}]}]}});