/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.dialog.add("image3",function(h){function C(){var a=this.getValue().match(D);(a=!(!a||0===parseInt(a[1],10)))||alert(d["invalid"+CKEDITOR.tools.capitalize(this.id)]);return a}function N(){function a(a,c){k.push(b.once(a,function(a){for(var b;b=k.pop();)b.removeListener();c(a)}))}var b=u.createElement("img"),k=[];return function(k,c,e){a("load",function(){var a=E(b);c.call(e,b,a.width,a.height)});a("error",function(){c(null)});a("abort",function(){c(null)});b.setAttribute("src",(x.baseHref||
"")+k+"?"+Math.random().toString(16).substring(2))}}function F(){var a=this.getValue();v(!1);a!==y.data.src?(G(a,function(a,b,d){v(!0);if(!a)return l(!1);c.setValue(!1===h.config.image3_prefillDimensions?0:b);e.setValue(!1===h.config.image3_prefillDimensions?0:d);m=b;n=d;l(H.checkHasNaturalRatio(a))}),p=!0):p?(v(!0),c.setValue(q),e.setValue(r),p=!1):v(!0)}function I(){if(f){var a=this.getValue();if(a&&(a.match(D)||l(!1),"0"!==a)){var b="width"==this.id,k=q||m,d=r||n,a=b?Math.round(a/k*d):Math.round(a/
d*k);isNaN(a)||(b?e:c).setValue(a)}}}function l(a){if(g){if("boolean"==typeof a){if(z)return;f=a}else a=c.getValue(),z=!0,(f=!f)&&a&&(a*=r/q,isNaN(a)||e.setValue(Math.round(a)));g[f?"removeClass":"addClass"]("cke_btn_unlocked");g.setAttribute("aria-checked",f);CKEDITOR.env.hc&&g.getChild(0).setHtml(f?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function v(a){a=a?"enable":"disable";c[a]();e[a]()}var D=/(^\s*(\d+)\s*$)|^$/i,J=CKEDITOR.tools.getNextId(),K=CKEDITOR.tools.getNextId(),b=h.lang.image3,
d=h.lang.common,O=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+b.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+
b.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:J,resetButtonId:K}),H=CKEDITOR.plugins.image3,x=h.config,A=!(!x.filebrowserImageBrowseUrl&&!x.filebrowserBrowseUrl),w=h.widgets.registered.image.features,E=H.getNatural,u,y,L,G,q,r,m,n,p,f,z,g,t,c,e,B,M=[{id:"src",type:"text",label:d.url,onKeyup:F,onChange:F,setup:function(a){this.setValue(a.data.src)},commit:function(a){a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];A&&M.push({type:"button",
id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:h.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:250,minHeight:100,onLoad:function(){u=this._.element.getDocument();G=N()},onShow:function(){y=this.widget;L=y.parts.image;p=z=f=!1;B=E(L);m=q=B.width;n=r=B.height},contents:[{id:"info",label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",children:M}]},{id:"alt",
type:"text",label:b.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())},validate:!0===h.config.image3_altRequired?CKEDITOR.dialog.validate.notEmpty(b.altMissing):null},{type:"hbox",widths:["100%"],requiredContent:w.dimension.requiredContent,children:[{type:"radio",width:"45px",id:"sizeimageby",label:b.sizeImageBy,onClick:function(){"px"==this.getValue()?(c.setValue(m),e.setValue(n)):(c.setValue(100),e.setValue(100))},items:[[b.pixels,"px"],[b.percentage,
"%"]],onLoad:function(){},setup:function(a){this.setValue(a.data.sizeImageBy)},commit:function(a){a.setData("sizeImageBy",this.getValue())}}]},{type:"hbox",widths:["25%","25%","50%"],requiredContent:w.dimension.requiredContent,children:[{type:"text",width:"45px",id:"width",label:d.width,validate:C,onKeyUp:I,onLoad:function(){c=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{type:"text",id:"height",width:"45px",label:d.height,validate:C,
onKeyUp:I,onLoad:function(){e=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",function(){this.addClass("cke_btn_over")},a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();g=u.getById(J);t=u.getById(K);g&&(b.addFocusable(g,4+A),g.on("click",function(a){l();a.data&&a.data.preventDefault()},
this.getDialog()),a(g));t&&(b.addFocusable(t,5+A),t.on("click",function(a){p?(c.setValue(m),e.setValue(n)):(c.setValue(q),e.setValue(r));a.data&&a.data.preventDefault()},this),a(t))},setup:function(a){l(a.data.lock)},commit:function(a){a.setData("lock",f)},html:O}]},{type:"hbox",id:"alignment",requiredContent:w.align.requiredContent,children:[{id:"align",type:"radio",items:[[d.alignNone,"none"],[d.alignLeft,"left"],[d.alignCenter,"center"],[d.alignRight,"right"]],label:d.align,setup:function(a){this.setValue(a.data.align)},
commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:b.captioned,requiredContent:w.caption.requiredContent,setup:function(a){this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",this.getValue())}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:b.btnUpload,"for":["Upload",
"upload"]}]}]}});