/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.dialog.add("image3",function(k){function D(){var a=this.getValue().match(E);(a=!(!a||0===parseInt(a[1],10)))||alert(d["invalid"+CKEDITOR.tools.capitalize(this.id)]);return a}function O(){function a(a,b){e.push(l.once(a,function(a){for(var l;l=e.pop();)l.removeListener();b(a)}))}var l=t.createElement("img"),e=[];return function(e,b,f){a("load",function(){var a=F(l);b.call(f,l,a.width,a.height)});a("error",function(){b(null)});a("abort",function(){b(null)});l.setAttribute("src",(z.baseHref||
"")+e+"?"+Math.random().toString(16).substring(2))}}function G(){var a=this.getValue();u(!1);a!==v.data.src?(H(a,function(a,e,b){u(!0);if(!a)return p(!1);f.setValue(!1===k.config.image3_prefillDimensions?0:e);g.setValue(!1===k.config.image3_prefillDimensions?0:b);w=e;x=b;p(I.checkHasNaturalRatio(a))}),q=!0):q?(u(!0),f.setValue(m),g.setValue(n),q=!1):u(!0)}function J(){if(c){var a=this.getValue();if(a&&(a.match(E)||p(!1),"0"!==a)){var b="width"==this.id,e=m||w,d=n||x,a=b?Math.round(a/e*d):Math.round(a/
d*e);isNaN(a)||(b?g:f).setValue(a)}}}function p(a){if(h){if("boolean"==typeof a){if(A)return;c=a}else a=f.getValue(),A=!0,(c=!c)&&a&&(a*=n/m,isNaN(a)||g.setValue(Math.round(a)));h[c?"removeClass":"addClass"]("cke_btn_unlocked");h.setAttribute("aria-checked",c);CKEDITOR.env.hc&&h.getChild(0).setHtml(c?CKEDITOR.env.ie?"■":"▣":CKEDITOR.env.ie?"□":"▢")}}function u(a){a=a?"enable":"disable";f[a]();g[a]()}var E=/(^\s*(\d+)\s*$)|^$/i,K=CKEDITOR.tools.getNextId(),L=CKEDITOR.tools.getNextId(),b=k.lang.image3,
d=k.lang.common,P=(new CKEDITOR.template('\x3cdiv\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.lockRatio+'" class\x3d"cke_btn_locked" id\x3d"{lockButtonId}" role\x3d"checkbox"\x3e\x3cspan class\x3d"cke_icon"\x3e\x3c/span\x3e\x3cspan class\x3d"cke_label"\x3e'+b.lockRatio+'\x3c/span\x3e\x3c/a\x3e\x3ca href\x3d"javascript:void(0)" tabindex\x3d"-1" title\x3d"'+b.resetSize+'" class\x3d"cke_btn_reset" id\x3d"{resetButtonId}" role\x3d"button"\x3e\x3cspan class\x3d"cke_label"\x3e'+
b.resetSize+"\x3c/span\x3e\x3c/a\x3e\x3c/div\x3e")).output({lockButtonId:K,resetButtonId:L}),I=CKEDITOR.plugins.image3,z=k.config,B=!(!z.filebrowserImageBrowseUrl&&!z.filebrowserBrowseUrl),y=k.widgets.registered.image.features,F=I.getNatural,t,v,M,H,m,n,w,x,q,c,A,h,r,f,g,C,N=[{id:"src",type:"text",label:d.url,onKeyup:G,onChange:G,setup:function(a){this.setValue(a.data.src)},commit:function(a){a.setData("src",this.getValue())},validate:CKEDITOR.dialog.validate.notEmpty(b.urlMissing)}];B&&N.push({type:"button",
id:"browse",style:"display:inline-block;margin-top:14px;",align:"center",label:k.lang.common.browseServer,hidden:!0,filebrowser:"info:src"});return{title:b.title,minWidth:250,minHeight:100,onLoad:function(){t=this._.element.getDocument();H=O()},onShow:function(){v=this.widget;M=v.parts.image;q=A=c=!1;C=F(M);w=m=C.width;x=n=C.height},contents:[{id:"info",label:b.infoTab,elements:[{type:"vbox",padding:0,children:[{type:"hbox",widths:["100%"],className:"cke_dialog_image_url",children:N}]},{id:"alt",
type:"text",label:b.alt,setup:function(a){this.setValue(a.data.alt)},commit:function(a){a.setData("alt",this.getValue())},validate:!0===k.config.image3_altRequired?CKEDITOR.dialog.validate.notEmpty(b.altMissing):null},{type:"hbox",widths:["100%"],requiredContent:y.dimension.requiredContent,children:[{type:"radio",width:"45px",id:"sizeimageby",label:b.sizeImageBy,onChange:function(){var a=this.getValue(),b={width:f.getValue(),height:g.getValue()},e=v.wrapper.getParent().getClientRect(),d=e.width,e=
e.height,c={width:0,height:0};"px"==a?(c.width=Math.round(b.width/100*d),c.height=Math.round(n/m*c.width)):(c.height=Math.round(b.height/e*100),c.width=Math.round(b.width/d*100));b=c;f.setValue(b.width);g.setValue(b.height)},items:[[b.pixels,"px"],[b.percentage,"%"]],onLoad:function(){},setup:function(a){this.setValue(a.data.sizeImageBy)},commit:function(a){a.setData("sizeImageBy",this.getValue())}}]},{type:"hbox",widths:["25%","25%","50%"],requiredContent:y.dimension.requiredContent,children:[{type:"text",
width:"45px",id:"width",label:d.width,validate:D,onKeyUp:J,onLoad:function(){f=this},setup:function(a){this.setValue(a.data.width)},commit:function(a){a.setData("width",this.getValue())}},{type:"text",id:"height",width:"45px",label:d.height,validate:D,onKeyUp:J,onLoad:function(){g=this},setup:function(a){this.setValue(a.data.height)},commit:function(a){a.setData("height",this.getValue())}},{id:"lock",type:"html",style:"margin-top:18px;width:40px;height:20px;",onLoad:function(){function a(a){a.on("mouseover",
function(){this.addClass("cke_btn_over")},a);a.on("mouseout",function(){this.removeClass("cke_btn_over")},a)}var b=this.getDialog();h=t.getById(K);r=t.getById(L);h&&(b.addFocusable(h,4+B),h.on("click",function(a){p();a.data&&a.data.preventDefault()},this.getDialog()),a(h));r&&(b.addFocusable(r,5+B),r.on("click",function(a){q?(f.setValue(w),g.setValue(x)):(f.setValue(m),g.setValue(n));a.data&&a.data.preventDefault()},this),a(r))},setup:function(a){p(a.data.lock)},commit:function(a){a.setData("lock",
c)},html:P}]},{type:"hbox",id:"alignment",requiredContent:y.align.requiredContent,children:[{id:"align",type:"radio",items:[[d.alignNone,"none"],[d.alignLeft,"left"],[d.alignCenter,"center"],[d.alignRight,"right"]],label:d.align,setup:function(a){this.setValue(a.data.align)},commit:function(a){a.setData("align",this.getValue())}}]},{id:"hasCaption",type:"checkbox",label:b.captioned,requiredContent:y.caption.requiredContent,setup:function(a){this.setValue(a.data.hasCaption)},commit:function(a){a.setData("hasCaption",
this.getValue())}}]},{id:"Upload",hidden:!0,filebrowser:"uploadButton",label:b.uploadTab,elements:[{type:"file",id:"upload",label:b.btnUpload,style:"height:40px"},{type:"fileButton",id:"uploadButton",filebrowser:"info:src",label:b.btnUpload,"for":["Upload","upload"]}]}]}});